service: local-lambda-service

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

functions:
  processSQSMessage:
    handler: processor.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-queue

plugins:
  - serverless-offline-sqs
  - serverless-offline
